name: Sync from Organization Repo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo (this one)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Clone source (organization private repo)
        env:
          ORG_ACCESS_TOKEN: ${{ secrets.TOKEN_REPO }} 
        run: |
          # A CLONAGEM É FEITA NA RAIZ (./)
          git clone --depth=1 https://x-access-token:${ORG_ACCESS_TOKEN}@github.com/FieldFlowJJ/FIELD-FLOW-FRONTED.git source-repo || { echo "Erro na clonagem. Verifique o token ou a URL."; exit 1; }
          
          # Entra na pasta clonada para garantir que a branch main esteja pronta
          cd source-repo
          git checkout main
          # Sai da pasta para que o próximo step de limpeza rode na raiz (IMPORTANTE!)
          cd ..

      - name: Sync files
        run: |
          # 1. Limpa o diretório de trabalho local (EXCETO a pasta .git e a pasta recém-clonada)
          # A exclusão da pasta source-repo é crucial, já que ela será removida no rsync
          find . -maxdepth 1 ! -name .git ! -name . -name source-repo -exec rm -rf {} \;
          
          # 2. Copia o conteúdo da pasta clonada (source-repo/) para a raiz (./)
          #    --exclude='.git' evita que o rsync tente copiar o repositório git da origem.
          rsync -av --delete --exclude='.git' source-repo/ ./
          
          # 3. Remove a pasta de origem, pois a cópia foi feita (limpeza final)
          rm -rf source-repo

      - name: Commit and push changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "Nenhuma alteração detectada. Nada para enviar."
            exit 0
          fi
          git commit -m "🔄 Sync from organization repo [auto]"
          git push origin main