name: Sync from Organization Repo

on:
  workflow_dispatch:        # Permite rodar manualmente
  schedule:
    - cron: "0 */6 * * *"   # Executa a cada 6 horas (ajuste se quiser)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo (this one)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Clone source (organization private repo)
        env:
          ORG_ACCESS_TOKEN: ${{ secrets.TOKEN_REPO }} 
        run: |
          # Clonagem bem-sucedida!
          git clone --depth=1 https://x-access-token:${ORG_ACCESS_TOKEN}@github.com/FieldFlowJJ/FIELD-FLOW-FRONTED.git source-repo || { echo "Erro na clonagem. Verifique o token ou a URL."; exit 1; }
          
          # Checkout dentro da pasta clonada
          cd source-repo
          git checkout main
          # NÃO VOLTAMOS AQUI. O próximo passo rodará na raiz, onde source-repo é visível.

      - name: Sync files
        run: |
          # 1. Limpa o diretório de trabalho local (EXCETO a pasta .git)
          # A pasta source-repo agora é visível neste nível.
          find . -maxdepth 1 ! -name .git ! -name . -exec rm -rf {} \;
          
          # 2. Copia o conteúdo da pasta clonada para a raiz
          rsync -av --delete --exclude='.git' source-repo/ ./

      - name: Commit and push changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "Nenhuma alteração detectada. Nada para enviar."
            exit 0
          fi
          git commit -m "🔄 Sync from organization repo [auto]"
          git push origin main