name: Sync from Organization Repo

on:
  workflow_dispatch:        # Permite rodar manualmente
  schedule:
    - cron: "0 */6 * * *"   # Executa a cada 6 horas (ajuste se quiser)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo (this one)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Clone source (organization private repo)
        env:
          ORG_ACCESS_TOKEN: ${{ secrets.TOKEN_REPO }} 
        run: |
          # 1. Clona o repositório, garantindo que a pasta 'source-repo' seja criada.
          # O token é injetado via URL.
          git clone https://x-access-token:${ORG_ACCESS_TOKEN}@github.com/FieldFlowJJ/FIELD-FLOW-FRONTED.git source-repo || { echo "Erro na clonagem. Verifique o token ou a URL."; exit 1; }
          
          # 2. Entra na pasta clonada
          cd source-repo
          
          # 3. Faz o checkout da branch principal
          git checkout main
          
          # 4. Volta para a raiz do repositório de destino (MUITO IMPORTANTE para os comandos seguintes)
          cd ..

      - name: Sync files
        run: |
          # 1. Limpa o diretório de trabalho local (EXCETO a pasta .git)
          find . -maxdepth 1 ! -name .git ! -name . -exec rm -rf {} \;
          
          # 2. Copia o conteúdo da pasta clonada para a raiz
          rsync -av --delete --exclude='.git' source-repo/ ./

      - name: Commit and push changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "Nenhuma alteração detectada. Nada para enviar."
            exit 0
          fi
          git commit -m "🔄 Sync from organization repo [auto]"
          git push origin main